import type { Product } from "./store"

export const products: Product[] = [
  // Smartphones
  {
    id: "phone-1",
    name: "Galaxy S24 Ultra",
    nameAr: "جالاكسي S24 الترا",
    price: 399.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "smartphones",
    description: "Flagship smartphone with advanced AI features, stunning display, and powerful performance",
    descriptionAr: "هاتف ذكي رائد مع ميزات الذكاء الاصطناعي المتقدمة وشاشة مذهلة وأداء قوي",
    specs: {
      Display: '6.8" Dynamic AMOLED 2X',
      Processor: "Snapdragon 8 Gen 3",
      RAM: "12GB",
      Storage: "256GB",
      Camera: "200MP + 50MP + 12MP + 10MP",
      Battery: "5000mAh",
    },
    inStock: true,
    rating: 4.8,
  },
  {
    id: "phone-2",
    name: "iPhone 15 Pro Max",
    nameAr: "آيفون 15 برو ماكس",
    price: 429.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "smartphones",
    description: "Premium iPhone with titanium design, A17 Pro chip, and revolutionary camera system",
    descriptionAr: "آيفون متميز بتصميم تيتانيوم ومعالج A17 Pro ونظام كاميرا ثوري",
    specs: {
      Display: '6.7" Super Retina XDR',
      Processor: "A17 Pro",
      RAM: "8GB",
      Storage: "256GB",
      Camera: "48MP + 12MP + 12MP",
      Battery: "4422mAh",
    },
    inStock: true,
    rating: 4.9,
  },
  {
    id: "phone-3",
    name: "Pixel 8 Pro",
    nameAr: "بيكسل 8 برو",
    price: 349.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "smartphones",
    description: "Google's AI-powered smartphone with exceptional camera and pure Android experience",
    descriptionAr: "هاتف جوجل الذكي المدعوم بالذكاء الاصطناعي مع كاميرا استثنائية وتجربة أندرويد نقية",
    specs: {
      Display: '6.7" LTPO OLED',
      Processor: "Google Tensor G3",
      RAM: "12GB",
      Storage: "128GB",
      Camera: "50MP + 48MP + 48MP",
      Battery: "5050mAh",
    },
    inStock: true,
    rating: 4.7,
  },

  // Laptops
  {
    id: "laptop-1",
    name: 'MacBook Pro 16"',
    nameAr: "ماك بوك برو 16 بوصة",
    price: 899.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "laptops",
    description: "Powerful laptop with M3 Pro chip, brilliant display, and all-day battery life",
    descriptionAr: "لابتوب قوي مع معالج M3 Pro وشاشة رائعة وبطارية تدوم طوال اليوم",
    specs: {
      Display: '16.2" Liquid Retina XDR',
      Processor: "Apple M3 Pro",
      RAM: "18GB",
      Storage: "512GB SSD",
      Graphics: "Integrated",
      Battery: "Up to 22 hours",
    },
    inStock: true,
    rating: 4.9,
  },
  {
    id: "laptop-2",
    name: "Dell XPS 15",
    nameAr: "ديل XPS 15",
    price: 649.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "laptops",
    description: "Premium Windows laptop with stunning InfinityEdge display and powerful performance",
    descriptionAr: "لابتوب ويندوز متميز مع شاشة InfinityEdge مذهلة وأداء قوي",
    specs: {
      Display: '15.6" OLED 4K',
      Processor: "Intel Core i7-13700H",
      RAM: "16GB",
      Storage: "1TB SSD",
      Graphics: "NVIDIA RTX 4050",
      Battery: "Up to 12 hours",
    },
    inStock: true,
    rating: 4.6,
  },
  {
    id: "laptop-3",
    name: "ThinkPad X1 Carbon",
    nameAr: "ثينك باد X1 كاربون",
    price: 549.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "laptops",
    description: "Ultra-light business laptop with legendary keyboard and military-grade durability",
    descriptionAr: "لابتوب أعمال خفيف للغاية مع لوحة مفاتيح أسطورية ومتانة عسكرية",
    specs: {
      Display: '14" 2.8K OLED',
      Processor: "Intel Core i7-1365U",
      RAM: "16GB",
      Storage: "512GB SSD",
      Graphics: "Integrated Iris Xe",
      Battery: "Up to 15 hours",
    },
    inStock: true,
    rating: 4.7,
  },

  // Tablets
  {
    id: "tablet-1",
    name: 'iPad Pro 12.9"',
    nameAr: "آيباد برو 12.9 بوصة",
    price: 399.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "tablets",
    description: "Professional tablet with M2 chip, Liquid Retina XDR display, and Apple Pencil support",
    descriptionAr: "تابلت احترافي مع معالج M2 وشاشة Liquid Retina XDR ودعم Apple Pencil",
    specs: {
      Display: '12.9" Liquid Retina XDR',
      Processor: "Apple M2",
      RAM: "8GB",
      Storage: "256GB",
      Camera: "12MP + 10MP",
      Battery: "Up to 10 hours",
    },
    inStock: true,
    rating: 4.8,
  },
  {
    id: "tablet-2",
    name: "Galaxy Tab S9 Ultra",
    nameAr: "جالاكسي تاب S9 الترا",
    price: 449.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "tablets",
    description: "Premium Android tablet with massive display, S Pen included, and desktop-class performance",
    descriptionAr: "تابلت أندرويد متميز مع شاشة ضخمة وقلم S Pen مُضمّن وأداء بمستوى سطح المكتب",
    specs: {
      Display: '14.6" Dynamic AMOLED 2X',
      Processor: "Snapdragon 8 Gen 2",
      RAM: "12GB",
      Storage: "256GB",
      Camera: "13MP + 8MP",
      Battery: "11200mAh",
    },
    inStock: true,
    rating: 4.7,
  },

  // Smartwatches
  {
    id: "watch-1",
    name: "Apple Watch Ultra 2",
    nameAr: "آبل ووتش الترا 2",
    price: 299.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "smartwatches",
    description: "Ultimate sports and adventure watch with precision GPS and rugged titanium design",
    descriptionAr: "ساعة رياضية ومغامرات نهائية مع GPS دقيق وتصميم تيتانيوم متين",
    specs: {
      Display: '1.92" Always-On Retina',
      Processor: "S9 SiP",
      Battery: "Up to 36 hours",
      WaterResistance: "100m",
      Sensors: "Heart rate, ECG, Blood O2, Temperature",
      Connectivity: "LTE, GPS, WiFi, Bluetooth",
    },
    inStock: true,
    rating: 4.9,
  },
  {
    id: "watch-2",
    name: "Galaxy Watch 6 Classic",
    nameAr: "جالاكسي ووتش 6 كلاسيك",
    price: 199.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "smartwatches",
    description: "Premium smartwatch with rotating bezel, comprehensive health tracking, and elegant design",
    descriptionAr: "ساعة ذكية متميزة مع إطار دوار وتتبع صحي شامل وتصميم أنيق",
    specs: {
      Display: '1.5" Super AMOLED',
      Processor: "Exynos W930",
      Battery: "Up to 40 hours",
      WaterResistance: "5ATM + IP68",
      Sensors: "BioActive, Temperature, Barometer",
      Connectivity: "LTE, GPS, WiFi, Bluetooth",
    },
    inStock: true,
    rating: 4.6,
  },

  // Headphones
  {
    id: "headphones-1",
    name: "AirPods Pro (2nd Gen)",
    nameAr: "إيربودز برو (الجيل الثاني)",
    price: 89.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "headphones",
    description: "Premium wireless earbuds with adaptive audio, active noise cancellation, and spatial audio",
    descriptionAr: "سماعات لاسلكية متميزة مع صوت متكيف وإلغاء ضوضاء نشط وصوت مكاني",
    specs: {
      Type: "In-Ear True Wireless",
      NoiseCancellation: "Active ANC + Transparency",
      Battery: "6 hours (30 with case)",
      Connectivity: "Bluetooth 5.3",
      Features: "Spatial Audio, Adaptive Audio, MagSafe",
      WaterResistance: "IPX4",
    },
    inStock: true,
    rating: 4.8,
  },
  {
    id: "headphones-2",
    name: "Sony WH-1000XM5",
    nameAr: "سوني WH-1000XM5",
    price: 129.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "headphones",
    description: "Industry-leading noise canceling over-ear headphones with exceptional sound quality",
    descriptionAr: "سماعات فوق الأذن بإلغاء ضوضاء رائد في الصناعة مع جودة صوت استثنائية",
    specs: {
      Type: "Over-Ear Wireless",
      NoiseCancellation: "Industry-leading ANC",
      Battery: "Up to 30 hours",
      Connectivity: "Bluetooth 5.2, LDAC",
      Features: "Multipoint, Speak-to-Chat, Hi-Res Audio",
      Weight: "250g",
    },
    inStock: true,
    rating: 4.9,
  },

  // Cameras
  {
    id: "camera-1",
    name: "Sony A7 IV",
    nameAr: "سوني A7 IV",
    price: 899.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "cameras",
    description: "Professional mirrorless camera with 33MP sensor, 4K 60fps video, and advanced autofocus",
    descriptionAr: "كاميرا احترافية بدون مرآة مع مستشعر 33 ميجابكسل وفيديو 4K 60fps وتركيز تلقائي متقدم",
    specs: {
      Sensor: "33MP Full-Frame CMOS",
      Video: "4K 60p 10-bit 4:2:2",
      ISO: "100-51200 (exp. 50-204800)",
      Autofocus: "759-point PDAF",
      Stabilization: "5.5-stop IBIS",
      Connectivity: "WiFi, USB-C, HDMI",
    },
    inStock: true,
    rating: 4.8,
  },

  // Gaming
  {
    id: "gaming-1",
    name: "PlayStation 5 Pro",
    nameAr: "بلايستيشن 5 برو",
    price: 499.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "gaming",
    description: "Next-gen gaming console with 8K support, ultra-fast SSD, and ray tracing technology",
    descriptionAr: "جهاز ألعاب الجيل القادم مع دعم 8K وSSD فائق السرعة وتقنية ray tracing",
    specs: {
      CPU: "AMD Zen 2 8-core",
      GPU: "AMD RDNA 3 36 CUs",
      RAM: "16GB GDDR6",
      Storage: "2TB SSD",
      Resolution: "Up to 8K",
      Features: "Ray Tracing, 3D Audio, HDR",
    },
    inStock: false,
    rating: 4.9,
  },
  {
    id: "gaming-2",
    name: "ROG Ally Handheld",
    nameAr: "روج آلاي المحمول",
    price: 299.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "gaming",
    description: "Portable Windows gaming handheld with powerful AMD processor and 120Hz display",
    descriptionAr: "جهاز ألعاب ويندوز محمول مع معالج AMD قوي وشاشة 120Hz",
    specs: {
      Display: '7" FHD 120Hz IPS',
      Processor: "AMD Ryzen Z1 Extreme",
      RAM: "16GB",
      Storage: "512GB SSD",
      Battery: "Up to 3 hours gaming",
      OS: "Windows 11",
    },
    inStock: true,
    rating: 4.5,
  },

  // Accessories
  {
    id: "accessory-1",
    name: "MagSafe Power Bank",
    nameAr: "بطارية ماج سيف المحمولة",
    price: 39.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "accessories",
    description: "Wireless magnetic power bank with 10000mAh capacity and fast charging support",
    descriptionAr: "بطارية محمولة مغناطيسية لاسلكية بسعة 10000 مللي أمبير ودعم الشحن السريع",
    specs: {
      Capacity: "10000mAh",
      Output: "15W MagSafe, 20W USB-C PD",
      Input: "USB-C 18W",
      Weight: "220g",
      Features: "Magnetic attachment, Pass-through charging",
      Compatibility: "iPhone 12 and later",
    },
    inStock: true,
    rating: 4.6,
  },
  {
    id: "accessory-2",
    name: "USB-C Hub 7-in-1",
    nameAr: "مركز USB-C 7 في 1",
    price: 29.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "accessories",
    description: "Versatile USB-C hub with HDMI, USB 3.0, SD card reader, and power delivery",
    descriptionAr: "مركز USB-C متعدد الاستخدامات مع HDMI وUSB 3.0 وقارئ بطاقات SD وتوصيل الطاقة",
    specs: {
      Ports: "HDMI 4K, 3x USB 3.0, SD/microSD, USB-C PD",
      HDMI: "4K@60Hz",
      USB: "5Gbps data transfer",
      PowerDelivery: "100W pass-through",
      Build: "Aluminum alloy",
      Compatibility: "MacBook, iPad, Windows laptops",
    },
    inStock: true,
    rating: 4.4,
  },
]

export function getProductsByCategory(category: string): Product[] {
  if (category === "all") return products
  return products.filter((p) => p.category === category)
}

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id)
}
